apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "voting-app.fullname" . }}
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "voting-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "voting-app.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "voting-app.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          env:
            - name: REDIS_HOST
              value: 'voting-redis-headless'
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: voting-redis
                  key: redis-password


