apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "voting.fullname" . }}
  labels:
    {{- include "voting.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "voting.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "voting.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "voting.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: REDIS_HOST
              value: {{ include "voting.redis.host" . }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "voting.redis.secrets" . }}
                  key: redis-password
            - name: PG_HOST
              value: {{ include "voting.postgresql.host" . }}
            - name: PG_USER
              value: 'postgres'
            - name: PG_DATABASE
              value: 'voting'
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "voting.postgresql.secrets" . }}
                  key: postgres-password

