apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "voting-worker.fullname" . }}
  labels:
    {{- include "voting-worker.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "voting-worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "voting-worker.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "voting-worker.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: REDIS_HOST
              value: 'voting-redis-master'
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: voting-redis
                  key: redis-password
            - name: PG_HOST
              value: 'voting-postgresql'
            - name: PG_USER
              value: 'postgres'
            - name: PG_DATABASE
              value: 'voting'
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: voting-postgresql
                  key: postgres-password

