apiVersion: v1
kind: Service
metadata:
  name: {{ include "voting-results.fullname" . }}
  labels:
    {{- include "voting-results.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
    protocol: TCP
  selector:
    matchLabels:
      {{- include "voting-results.selectorLabels" . | nindent 4 }}