apiVersion: v1
kind: Service
metadata:
  name: {{ include "voting.fullname" . }}
  labels:
    {{- include "voting.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
    protocol: TCP
  selector:
    {{- include "voting.selectorLabels" . | nindent 4 }}